### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AlexBrunetti** [github-jimjim/Pynfish#1]
There isn' any UCI protocol.
No way to run it in Arena. How did you do that?!

Thanks,
Alex

**Comment by github-jimjim** [comment]
Which Arena do you mean? I could make a Video on YouTube if you want to.
Jimmy

**Comment by AlexBrunetti** [comment]
Sorry, I was testing ui instead of main, that's why it wasn't working in the GUI! All good now.

Alex

**Comment by github-jimjim** [comment]
No problem. :)
